function [train_pred, test_pred, ... 
    train_nmse, test_nmse] = FitAndForecastARMAX(ar_order, x_order, ma_order, ...
                                                train_data, test_data, input, components)
% =========================================================================
train_comp = components{1};
test_comp = components{2};
train_input = input{1};
test_input = input{2};
dtds_train_data = train_data - train_comp;             
train = iddata(dtds_train_data, train_input, 'TimeUnit','months');
% ======== fit model ======================================================
model = armax(train, [ar_order [x_order] ma_order 1]);
train_pred = dtds_train_data + resid(train,model).y + train_comp;
% ======== compute train error ============================================
train_nmse = 1- min([1 ... 
                   power( ... 
                     norm( train_data - train_pred ) / ... 
                     norm( train_data - mean(train_data)) ... 
                         ,2) ... 
                ]);
% ======== forecast =======================================================
test_pred = forecast(model, train, numel(test_data), test_input);
test_pred = test_pred.y + test_comp;
% ======== compute test error =============================================
test_nmse = 1- min([1 ... 
                   power( ... 
                     norm( test_data - test_pred) / ... 
                     norm( test_data - mean(test_data)) ... 
                         ,2) ... 
                ]);
