function [train_pred, test_pred, train_nmse, test_nmse] = FitAndForecastARMA(ar_order, ma_order, train_data, test_data, components)
% =========================================================================
train_comp = components{1};
test_comp = components{2};
dtds_train_data = train_data - train_comp;
% ======== fit model ======================================================
model = estimate(arima(ar_order, 0, ma_order), dtds_train_data, 'Display', 'off');
residuals = infer(model, dtds_train_data);
train_pred = dtds_train_data + residuals + train_comp;
% ======== compute train error ============================================
train_nmse = 1- min([1 ... 
                   power( ... 
                     norm( train_data - train_pred ) / ... 
                     norm( train_data - mean(train_data)) ... 
                         ,2) ... 
                ]);
% ======== forecast =======================================================
[test_pred, ~] = forecast(model, numel(test_data), dtds_train_data);
test_pred = test_pred + test_comp;
% ======== compute test error =============================================
test_nmse = 1- min([1 ... 
                   power( ... 
                     norm( test_data - test_pred) / ... 
                     norm( test_data - mean(test_data)) ... 
                         ,2) ... 
                ]);
